on: workflow_dispatch
  #schedule:
  #   - cron: "* * * * *"

jobs:
  traffic:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: MultiPendulum traffic
      uses: sangonzal/repository-traffic-action@v0.1.4
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
    
    - name: Push test files
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
      with:
        source_file: './traffic/'
        destination_repo: ${{ secrets.MULTIPENDULUM_TRAFFIC_DESTINATION }}
        user_email: ${{ secrets._GITHUB_USER_EMAIL }}
        user_name: ${{ secrets._GITHUB_USERNAME }}
