on: workflow_dispatch
  #schedule:
  #   - cron: "* * * * *"

jobs:
  traffic:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: MultiPendulum traffic
      uses: sangonzal/repository-traffic-action@v0.1.4
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
    
    - name: Send mail
      uses: juanformoso/action-send-mail@1
      with:
        server_address: smtp.mail.yahoo.com
        server_port: 587
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: MultiPendulum traffic
        body: Test
        to: ${{ secrets.MAIL_USERNAME }}
        from: ${{ secrets.MAIL_USERNAME }}
        attachments: ./traffic/views.csv,./traffic/clones.csv,./traffic/plots.png
